CHollingworth/Lampray

- Lamp/Control/lampControl.h
Added the ability to reorder mods by dragging them around (you currently have to drag the mod name)
These changes also allow moving the mod table columns around, but column changes are not saved or restored.
> feat: Mod Drag and Drop Reordering

- Lamp/Menu/lampColour.h
- main.cpp
Adds a field on the Customize Lamp page to allow users to scale the font size. The size gets saved to file with the other options and gets loaded/applied on application start.
This should also reset to the original scale when the reset button is pressed.
I think the ideal solution would be to change the actual font-size instead of changing the font scale (scaling can make things blurry), but I was not sure how to accomplish that.
> feat: Configurable font size/scale

- Lamp/Control/lampControl.h
This adds another table flag to the mods table that lets users hide/show columns by right-clicking the table header.
This can help reduce clutter for users that don't care about particular columns (such as the Last Updated column), or when they don't need to access a column often (such as the Remove Mod column).
> feat: Enable hiding table columns

- Lamp/Control/lampControl.h
- Lamp/Menu/lampColour.h
Added a new configurable color `Colour_ButtonAlt`, and used that color for the "Enabled" button on the mods table.
Having a different color for the enabled/disabled button state can be useful for quickly determining which mods are and are not enabled at a glance.
I did not put much consideration/thought into the default color that I used (#179642FF). I would recommend taking a look and seeing if you would prefer using a different color as the default.
> feat: Configurable alternate button color

- Lamp/Menu/lampColour.h
- main.cpp
The initial colors loaded when the application has not yet been run (or when the config file is deleted) and the colors set when the reset button was clicked were different.
This should resolve that by removing an extra, unused default color declaration, and by referencing the default colors defined in `lampColours.h`, instead of having a separate set of values hard-coded in `main.cpp`.
I also made an extremely minor change to the "default" ButtonAlt color so that the RGB values do not change on reset.
> fix: Fixed inconsistent colors between init and reset

- Lamp/Menu/lampColour.h
- Lamp/Menu/lampMenu.cpp
- main.cpp
Added an option to disable the automatic check for updates when the application starts. This also add and item to the menu to manually check for updates.
By default, the stored value in the configuration file would be a 1 or 0, but the checks would also support "false" as a valid value to turn it off. If the value in the configuration is not 0 or "false", then we assume that it is set to true, and do the update check.
I wasn't sure if this is something you would want to include, but figured I would make a pull request in case you don't mind having it. For some users (such as myself), this removes (what I would consider) unnecessary network traffic. I haven't tested this, but it could also technically provide a slight improvement in the startup time when disabled, as this check was done …
> feat: Add configuration for disabling automatic update check and add a a button for manual checks

- Lamp/Control/lampControl.h
This re-enables deleting the managed mod files when the delete button is clicked, which would be the expected behavior.
I also hid the delete button when a mod is enabled to prevent any issues from deleting an active/enabled/deployed mod.
> fix: Re-enable deleting mod files with delete button and hide button on enabled mods

- Lamp/Control/lampControl.h
This should fix a crash that could happen when deleting mods, which seems to have been introduced with the disabled button change in 65c0c4241a4906884b1fb1265b7bebf0d96da6a8.
I did not fully explore the cause, but it seemed like the crash would occur when you had at least 1 mod enabled and deleted another mod. I believe this was because we begin a disabled section (`BeginDisabled`), but we do not properly close out that section when a mod is deleted.
> fix: a crash that can happen when deleting mods

- Lamp/Control/lampControl.h
This change attempts to highlight the mod row when you hover over it. Right now, it uses `Colour_SearchHighlight` for the highlight color.
There are some issues with how this currently works, but I have not figured out a way to make it work better. Right now, I have it checking for if the user is hovering over each item in the row individually, and applying the highlighting to the whole row if they are. This adds some messiness to the code that I am not a fan of (I feel like there *should* be some way to check if the user is hovering over the row or any children in a single check, rather than having to check after each item). This also means that the highlight effect gets dropped as you move between elements (for example, if you have a short mod name, the highlight goes away as you move …
> feat: Highlight mods on hover

- game-data/BG3/BG3.cpp
- game-data/C77/C77.cpp
This re-adds some file checking for adding files to BG3 and C77. It should compare the entire filename and make sure that the file is not already added.
While 6b5a8f2 did fix the issue in #78, I believe this change may provide some additional benefits by preventing duplicate files from being added. Having duplicate files could cause some unexpected behavior if you have multiple entries of a mod and delete any of those entries (while still keeping at least 1 entry for the mod).
> feat: Add mod filename checks to prevent adding duplicate mods

- Lamp/Base/lampBase.h
- Lamp/Filesystem/lampExtract.cpp
- Lamp/Parse/lampParse.h
- game-data/BG3/BG3.cpp
This should get rid of some minor warnings that come up during compile.
These mostly seemed to be related to missing returns, when a boolean return value was expected from the function.
> fix: Resolve minor compile warnings

- Lamp/Control/lampControl.h
This adds a context menu on the mod name with options to move the mod to the top or bottom of the load order.
This should help with moving mods around on larger mod lists.
I also modified how the drag and drop moves mods to use the new `moveModTo` function I added. I think this simplifies the logic visually on top of using the other existing functions for moving mods instead of relying on something custom.
> feat: Add context menu for moving mods to top or bottom

- Lamp/Menu/lampMenu.cpp
- Lamp/Menu/lampMenu.h
- main.cpp
Adds a quit button to the main menu.
This option may feel nicer to some users over requiring the use of the close button on the window.
I was hoping for a somewhat 'cleaner' way of doing this (such as by manually triggering an `SDL_QUIT` event from the menu), but I have not yet figured out if that is possible. If you have a better way of handling this, feel free to close this PR or let me know. Otherwise, I believe this should work fine.
> feat: Add quit button to the menu

- game-data/C77/C77.cpp
From what I have seen, REDMods typically want to be installed in `/mods` (as opposed to `/REDMod`). This should fix allowing them to install in the `/mods` directory.
I am basing this on what I see in mods like <https://www.nexusmods.com/cyberpunk2077/mods/5266> and <https://www.nexusmods.com/cyberpunk2077/mods/11479>. I have left the previous `/REDMod`, as I am unsure if some mods might need to install files there.
> fix: Fix installing REDMod into the /mods directory

- Lampray/Control/lampControl.h
This should fix an issue where a separator "name" would be truncated when slashes are used as part of the name.
> fix: Display full separator name when slashes are used

- Lampray/Control/lampConfig.cpp
> fix: Installed p7zip not found due to path being omitted

- Lampray/Control/lampControl.h
- Lampray/Lang/lampLang.h
This adds some text to the buttons for choosing the relevant game directories, which should make the buttons more obviously clickable for first-time users.
> feat: Add default text for game path configuration buttons

- Lampray/Control/lampNotification.h
- Lampray/Lang/lampLang.h
- Lampray/Menu/lampCustomise .h
- Lampray/Menu/lampMenu.cpp
- Lampray/Menu/lampMenu.h
- main.cpp
- third-party/imgui/imconfig.h
- third-party/imgui/imgui.cpp
- third-party/imgui/imgui.h
- third-party/imgui/imgui_demo.cpp
- third-party/imgui/imgui_draw.cpp
- third-party/imgui/imgui_impl_sdl2.cpp
- third-party/imgui/imgui_impl_sdl2.h
- third-party/imgui/imgui_impl_sdlrenderer2.cpp
- third-party/imgui/imgui_impl_sdlrenderer2.h
- third-party/imgui/imgui_internal.h
- third-party/imgui/imgui_tables.cpp
- third-party/imgui/imgui_widgets.cpp
- third-party/imgui/imstb_textedit.h
Adds a basic notification system to help us notify users of various errors, warnings, etc.
**As part of this change, I had to bump the ImGui version to 1.90, and I have not fully re-tested the interface.**
Some of the main changes include:
- Adding a new file at `Lampray/Control/lampNotification.h` to provide functionality
- Bumping the ImGui version to 1.90 to make use of recently added ChildWindow flags for auto-height resizing.
- Fixing an issue with changing the font scale (the bug likely showed itself due to the ImGui update)
- Added an error notification for when we fail to find the 7z.so file.
To add a notification for display, you would just need to include the  `Lampray/Control/lampNotification.h` file and then call the related function with your notification message:
- …
> feat: Add a basic notification system

- Lampray/Control/lampNotification.h
Without this include statement, both GCC and clang fails building, giving "incomplete type" errors.
> build: add missing include statement in lampNotification.h

- Lampray/Base/lampBase.h
- Lampray/Control/lampControl.h
- Lampray/Control/lampNotification.h
- Lampray/Filesystem/lampUpdate.cpp
- Lampray/Menu/lampMenu.cpp
Some Linux distros uses `-Wformat -Werror=format-security` flags when
building C/C++ projects by default. This makes harder to build Lampray
on such distros with default build flags.
> build: Fix -Wformat warnings

- Lampray/Control/lampControl.h
Add text input fields for game configuration paths, which will allow users to type in or copy+paste in directories instead of having to use the system file chooser.
This should address issue #120.
> feat: Add text input fields for entering game configuration paths (#120)

- .github/workflows/pr-preview.yml
- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- CONTRIBUTING.md
- com.github.chollingworth.Lampray.yml
- docs/building-from-source.md
Lampray will now build and publish flatpaks.
Furthermore to facilitate hallway testing, when you comment in a PR `/build` a PRs can have a flatpak generated as a artifact (not a release) and you'll see a comment link to the created preview flatpak.
This is useful for:
- the release PRs to get a preview of what a release is going to be like.
- fix and feature PRs: test if your changes are helpful.
> chore(ci): build and publish flatpak on release

- main.cpp
Add a line near the beginning of the log file, and in the output, containing the current Lampray version string (pulled from `Lampray/Filesystem/lampFS.h`).
This should be helpful in determining if a reported issue is from a current or outdated version of Lampray.
> feat: Include the current Lampray version in the log for debugging

- Lampray/Filesystem/lampExtract.cpp
- Lampray/Filesystem/lampIO.cpp
This re-enables attempted support for .rar files. It will attempt to decompress with Rar5 first, and fallback to the older Rar method if that fails.
If both methods fail, the user will get an error notification with the error messages from both attempts.
I tested with the main .rar files from <https://github.com/ssokolow/rar-test-files>. This successfully extracted the `testfile.rar5.rar` file, but still fails on the `testfile.rar3.rar` file, so support will probably still be spotty.
> feat: Re-enable rar support
